### ISSUE TITLE
Slideshow won't display if it contains only one slide

### ISSUE THREAD

**Issue by jeffwalker99** [parallelus/simple_theme_slider#1]
The slideshow won't display if it contains only one slide.

**Help Center topic** → http://para.llel.us/support/groups/goexplore/forum/topic/theme-options-not-responding/

**Comment by lesninsky** [comment]
This bug is related to owl carousel, so I have fixed it in the theme. Please see commit https://github.com/parallelus/GoExplore/commit/8ef5ae00df8f51a1c69d39fb94171656e83fc7df

**Comment by jeffwalker99** [comment]
@lesninsky 

Doesn't this mean that when we update GoExplore! with the latest version of this plugin, this fix will be lost?

**Comment by lesninsky** [comment]
No, since the fix is related to the theme.

**Comment by jeffwalker99** [comment]
Okay, thanks.
